from app.services.auth_service import (
    hash_password,
    verify_password,
    create_access_token,
    get_user_by_username,
    create_user,
    authenticate_user,
    get_current_user,
)

from app.services.habit_service import (
    get_habits_by_user,
    get_habit_by_id,
    create_habit,
    update_habit,
    delete_habit,
)

from app.services.habit_log_service import (
    toggle_habit_log,
    update_log_note,
    get_user_logs_for_date,
    get_user_logs_with_notes_for_date,
    get_recent_notes,
    get_weekly_completion,
    get_monthly_completion,
)

from app.services.challenge_service import (
    create_challenge,
    get_challenges_by_user,
    get_challenge_by_id,
    update_challenge,
    delete_challenge,
    calculate_challenge_progress,
    get_challenges_with_stats,
    get_active_challenge_for_habit,
)

from app.services.stats_service import (
    calculate_current_streak,
    calculate_total_completed,
    calculate_completion_rate,
    get_habits_with_stats,
    get_habit_with_stats,
    get_30day_trend,
    get_category_breakdown,
    get_monthly_completion_rates,
    get_habit_monthly_rates,
    get_overall_stats,
    get_dashboard_stats,
)

__all__ = [
    "hash_password",
    "verify_password",
    "create_access_token",
    "get_user_by_username",
    "create_user",
    "authenticate_user",
    "get_current_user",
    "get_habits_by_user",
    "get_habit_by_id",
    "create_habit",
    "update_habit",
    "delete_habit",
    "calculate_current_streak",
    "calculate_total_completed",
    "calculate_completion_rate",
    "get_habits_with_stats",
    "get_habit_with_stats",
    "toggle_habit_log",
    "update_log_note",
    "get_user_logs_for_date",
    "get_user_logs_with_notes_for_date",
    "get_recent_notes",
    "get_weekly_completion",
    "get_monthly_completion",
    "create_challenge",
    "get_challenges_by_user",
    "get_challenge_by_id",
    "update_challenge",
    "delete_challenge",
    "calculate_challenge_progress",
    "get_challenges_with_stats",
    "get_active_challenge_for_habit",
    "get_30day_trend",
    "get_category_breakdown",
    "get_monthly_completion_rates",
    "get_habit_monthly_rates",
    "get_overall_stats",
]
